### ISSUE TITLE
Fine-Tune and Measure Accuracy of Our Fingerprinting Keywords

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#220]
This is an issue to dig deeper into our custom list of fingerprinting keywords. Maybe we add more keywords after further investigation, maybe we remove certain words that create too many false positives, or maybe we come up with some kind of ruleset to decide if we've flagged correctly.

Also, snippet examples should be collected here.

<img width="324" alt="Screen Shot 2021-07-08 at 12 14 43 PM" src="https://user-images.githubusercontent.com/51685858/124957170-caa1b700-dfe6-11eb-9c7d-1d6ef81f94b9.png">
<img width="331" alt="Screen Shot 2021-07-08 at 12 14 51 PM" src="https://user-images.githubusercontent.com/51685858/124957193-d0979800-dfe6-11eb-9a4b-92be01a2d93a.png">

**Comment by SebastianZimmeck** [comment]
@danielgoldelman will look into this and make any changes necessary. And then when we do our systematic testing.

**Comment by SebastianZimmeck** [comment]
Nice, @danielgoldelman! As far as I am concerned, this modification can be merged once you think it is time.

**Comment by danielgoldelman** [comment]
Reformatted list to fit format of excel file that includes justification for the entries in the list, found [here](https://docs.google.com/spreadsheets/d/1YXqqBAvgDxdhgN42xbwdI0r8i7-5dM8ooA0vzipDO1A/edit?usp=sharing).
