### ISSUE TITLE
Develop Early Analysis Termination Algorithms/Heuristics

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#297]
Now that we're thinking about testing our extension (#289), keeping the memory/CPU usage down of our analysis would be ideal. Anecdotally, my fan often comes on while developing, so I think we'd do well to reduce complexity. 

My hunch is that we're unneccessarily searching through large requests (many characters) that could have been quickly identified as unlikely to be fruitful (create a label). 

Ideally, the termination algorithm would be lightweight. It will likely rely on some kind of context-specific heuristic. Maybe something that can quickly spot page content or functional code. It could even be as simple as analyzing only requests under a certain length if this gives us a favorable label-accuracy/complexity tradeoff.

**Whatever we come up with, this will be implemented as a default-enabled setting that can be toggled off if the user chooses.**

On this topic, it would also be good to get a sense for the time/space complexity while the extension is running:
1) from the development code
2) from the production code

Maybe we are lucky and the production code is much lighter weight but I am skeptical...

**Comment by notowen333** [comment]
After implementing the 100k cutoff described above (merged to [main](https://github.com/privacy-tech-lab/privacy-pioneer/pull/310)), the performance looks a lot better, but it's still going to need to be scaled back. 

This issue can stay open for new ideas/findings. If a more specific idea is explored, it should get its own issue.

**Comment by SebastianZimmeck** [comment]
@notowen333 created a [Google Doc](https://docs.google.com/document/d/1hyMjA_Ko4bc-OlC9-Ewf_lvEKsKmJ0d--Df35HQcIHk/edit?usp=sharing) to keep track of all the techniques for improving computational performance.

**Comment by notowen333** [comment]
In the end, adjusting which parts of the HTTP request we take in: 
- no more headers; looking at cookies separately

and not analyzing large requests: 
- terminating while the response data comes in

**was enough to make our extension work within CPU/memory bounds.** 

Other approaches could be explored in the future, but for now, we are in good shape and have managed to maintain the large majority of our functionality. 😄
