### ISSUE TITLE
Detect "Video Stream" Response Data to Improve Performance

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#315]
Related to #297 

Here's a specific idea for reducing complexity:

**Quickly tagging and ignoring response data that represents streamed content**. I don't think we're going to find anything useful in this data and it tends towards the larger end.

**Comment by notowen333** [comment]
Noting here that even after the new changes that improve performance significantly, loading twitch.tv brought CPU usage way up. I imagine this issue is relevant here.

**Comment by SebastianZimmeck** [comment]
@notowen333, do you think the video stream on twitch.tv was not detected? Or what could be the reason why the performance (I assume) is good on you YouTube but not on Twitch?

**Comment by notowen333** [comment]
Closing for now. Even on youtube/twitch/etc... our performance is good enough. Could re-open in the future as an additional optimization.
