### ISSUE TITLE
Scan Cookies On Page Load | Create Cookie Label

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#316]
As discussed in #314, with the pending changes to `Request` objects, we will no longer catch cookies that are set in request/response headers.

However, we can still look at cookies without catching them in the headers via the cookies API.
> My prefered solution for the cookie issue would be to use the [cookies API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) to scan through a page's cookies for watchlist items/coordinates. We could do this scan on the [page loaded event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event). I think this is lower cost than adding headers back. Also, this would allow us to add a `cookie` label if we find information there. 

The benefit of this solution is that we can:
- run specifically the watchlist/coordinate routines on cookies
- reduce the complexity of the overall analysis
- Give an additional `cookie` label when information is found in this routine.

So, for the backend, the tasks are:
- Interact with the cookies API to access a website's cookies
- Set up an analysis flow for these cookies
- Set up an event listener to initiate this flow on page load
- Add `cookie: true` property to evidence objects created from this routine

For the frontend, we should make this minimally complex:
- Add `cookie` badge for evidence objects with this property (Maybe this emoji appended to the end of the badge:  🍪 )
- Some kind of explanation either on hover for the cookie emoji or somewhere else.

So maybe a row of badges could look like this: **( Fine Location 🍪 ) (State)**

I think this choice in UI makes the most sense because `cookie` is a trait of the specific Evidence object; not higher up like `reqUrl` or `permission`.

**Comment by SebastianZimmeck** [comment]
Basically, the idea is to add a cookie label (in form of a cookie icon, for example) when evidence was found in a cookie. Here are [three examples for testing (cookies contain GPS location)](https://github.com/privacy-tech-lab/privacy-pioneer/issues/314#issuecomment-907541647).

**Comment by danielgoldelman** [comment]
^ backend implementation added, frontend changes next.

**Comment by danielgoldelman** [comment]
^ frontend changes implemented. Beginning testing. Note: Not my real IP.
<img width="351" alt="Screen Shot 2021-08-31 at 2 09 11 PM" src="https://user-images.githubusercontent.com/64672619/131554083-399d53f9-bd19-426f-8dec-6f3cf81860bb.png">
