### ISSUE TITLE
Throttle Individual Pages to Improve Performance

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#319]
Linked to #297 

Another idea for improving performance would be to allocate each unique page some set amount of effort, and then stop analyzing if that level is exceeded. Maybe, this could help with #315. Otherwise, it serves as a safeguard against over-exertion of our extension.

**Ideally, the level would be set so most websites/label creations are unaffected.**

**Comment by SebastianZimmeck** [comment]
@notowen333, do you imagine that based on time, number of requests processed (which brings us back a bit to what we had before), something else?

**Comment by notowen333** [comment]
Time after page load is the front-runner right now.

**Comment by SebastianZimmeck** [comment]
As @notowen333 clarified in our call today, reducing the number of requests would be actually different from what we had before, which only reduced the amount of labels but not the work being done.

**Comment by notowen333** [comment]
After some further investigation, I think we are actually in good enough shape here. I think I may have confused the CPU usage of Firefox Web Content (not us) and Firefox Web Extensions (us). Even streaming video, CPU usage is <5% on our end. Interestingly enough, the highest CPU usage is coming from React on the front-end. I'm going to close this issue.
