### ISSUE TITLE
Location form editing not functioning

### ISSUE THREAD

**Issue by danielgoldelman** [privacy-tech-lab/privacy-pioneer#321]
When you try to edit the location / street address form in the watchlist, there are no visual updates and you can only edit letter by letter. @Lr-Brown will take the lead.

See below:
In this example I tried to write the word "Here" after "Example Street", and I tried to delete "City" from "Example City". In the video you will see only the last letter "e" from "Here" being added, and you will see that only the "y" from "City" was deleted.

https://user-images.githubusercontent.com/64672619/131262818-24edfa1a-7f3b-4382-a011-2fc53218a32a.mov

**Comment by SebastianZimmeck** [comment]
Good find, @danielgoldelman!

**Comment by SebastianZimmeck** [comment]
@danielgoldelman took a look at this, but @Lr-Brown, you are probably in a better position. So, if you could check it out when you have time ...
