### ISSUE TITLE
Disallow Side-Scroll In Popup

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#332]
Using a track-pad, the popup "wiggles" right and left while scrolling. I think only up and down scroll should be permitted. I'd imagine this just requires some CSS in the right place.

**Comment by notowen333** [comment]
Took a little bit to find, but as I suspected this just required one line of css: `overflow-x: hidden`.  I found the right place to put it and committed straight to main (see above). Closing this issue.

**Comment by danielgoldelman** [comment]
^Note: This was a mistake. Issue should not be reopened
