### ISSUE TITLE
Labeling Methodology and Workflows

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#349]
# Overview
This is an issue to organize thinking surrounding labeling for the NLP approach. In #348 I described a first pass at labeling using doccano.

## Changes
From today's meeting we want to make a number of changes:
1. Separate out each example into its own file.
2. Separate coordinate label into lat/lng
3. Preprocess text before labeling (described below)
4. Host doccano in the cloud (Wesleyan, AWS, Azure, GC)

## Preprocessing
Before labeling, we want **to replace instances of data points with generics**.

#### Before
```
huffpost, Out Without Me\",\"Knoxville\",\"Lexington\",\"Madison\",\"Maxwell
 house\",\"Mayans\",\"Memphis\",\"Middletown\",\"Midsommar\",\"Monster\
",\"Music\",\"Narcos\",\"Newark\",\"Omaha\",\"Overland Park\",\"Ozark\",\
```
#### After
```
huffpost, Out Without Me\",\"Knoxville\",\"Lexington\",\"Madison\",\"Maxwell
 house\",\"Mayans\",\"Memphis\",\"<TARGET-CITY>\",\"Midsommar\",\"Monster\
",\"Music\",\"Narcos\",\"Newark\",\"Omaha\",\"Overland Park\",\"Ozark\",\
```
#### Before
```
de\":\"06106\",\"areaCode\":\"860\",\"connSpeed\":\"cable\",\
"latitude\":\"41.77\",\"longitude\":\"-72.68\",\"ipAddress\":\"73.238.148.75\",\"isEU\":false},\
"brandedContent\":true,\"sid\":\"d18cb39b-8ef9-4
```
#### After
```
de\":\"06106\",\"areaCode\":\"860\",\"connSpeed\":\"cable\",\
"latitude\":\"<TARGET-LAT>\",\"longitude\":\"<TARGET-LNG>\",\"ipAddress\
":\"<TARGET-IP>\",\"isEU\":false},\"brandedContent\":true,\"sid\":\"d18cb39b-8ef9-4
```

Then, after this preprocessing, we would give no labels in the first example and the appropriate labels (lat,lng,ip) in the second example.

## Cloud 
We want to host the Doccano in a place where we can all contribute to it.

@Lr-Brown suggested that we can use a Wesleyan server to host. This may be the simplest. If not, we can look into using one of the larger providers, Doccano suggests easy deployment to AWS and Azure in their docs. Maybe @Lr-Brown wants to take the lead here.

**Comment by notowen333** [comment]
I went ahead and implemented the described labeling changes, [here](https://github.com/privacy-tech-lab/privacy-pioneer-data-and-scripts/pull/16/commits/705b08d07b8a82dba6b90702c6747d0ea5de17f9).

The remaining task here is to look into shared hosting of a labeling tool.

**Comment by SebastianZimmeck** [comment]
@notowen333 explained today that we are for the most part clear about the data pipeline. If there is anything open on that end, we should get final clarity. Once we have that, the question may become how we can scale the different steps, e.g., capturing network traffic, labeling the data, ... . One way is to automate and another is to use the crowd, particularly, for labeling (e.g., Amazon Mechanical Turk, Prolific). Before investing time and effort in scaling, let's make sure that we really need it, though.

**Comment by SebastianZimmeck** [comment]
We have a more concrete idea here. @notowen333 will open a new issue on picking and hosting an annotation tool to collaborate online among all of us. @Lr-Brown will be working ultimately on that issue.
