### ISSUE TITLE
Rough idea of recall/precision of current approach

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#350]
@SebastianZimmeck mentioned in today's meeting that we want to have a rough idea of the strength of our current approach. 

In my mind, to get a sense of the precision (true positives flagged/total positives flagged) **we could just run PP and inspect its results by hand.** This could be done by someone in the next couple of weeks on a small sample of ten or so sites.

Recall (true positives flagged/total ground truth positives), on the other hand, runs into the larger "ground truth problems" that we have been struggling with when thinking about testing methodology. **I do not know how we can measure the "total ground truth positives" and so recall is much trickier.**

**Comment by SebastianZimmeck** [comment]
> In my mind, to get a sense of the precision (true positives flagged/total positives flagged) we could just run PP and inspect its results by hand.

Yes, that is good. We can fill in the ground truth in for the 25 sites in our [validation set](https://docs.google.com/spreadsheets/d/1RFE8V1wyybySIIi5rC7JaRhC95mIe53e-WZmUPvu7sw/edit?usp=sharing) for all the practices or a subset at least. Then, run PP and manually inspect.

>  I do not know how we can measure the "total ground truth positives" and so recall is much trickier.

I would say, manual inspection as well, right? I agree there is a much higher chance to miss a ground truth positive that was not recognized (i.e., identify a false negative classification). However, with 25 manual inspection seems tractable for the most part.

I am pretty sure you mean the same thing as below, @notowen333, but just to clarify: 
- Precision = True Positives / (True Positives + False Positives)
- Recall = True Positives / (True Positives + False Negatives)

So, if anyone wants to take the lead on this and see how it goes, please go ahead ...

(cc'ing @harkous)
