### ISSUE TITLE
Integrate NLP framework into PP

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#351]
In tandem with #349, #348 we want to see that it would be possible to integrate NLP inference into PP. This issue can organize the work that goes along with this. 

@danielgoldelman is taking the lead here.

**Comment by SebastianZimmeck** [comment]
> @danielgoldelman is taking the lead here.

And @Lr-Brown will also work on this.

**Comment by Lr-Brown** [comment]
This week I have been familiarizing myself with TensorFlow so that I can better assist @danielgoldelman in this issue.

**Comment by SebastianZimmeck** [comment]
We had a nice discussion today that led to two questions:
1. Is the computational performance of our ML/NLP models doable with the current structure of Privacy Pioneer? Our sense is yes, but we need to test this a bit more. Possibly, trying some batch processing will be informative.
2. How can we integrate our planned ML/NLP models into the current codebase? Could we essentially have a separate module that we could easily integrate, or would the new techniques necessitate a substantial structural rewrite of our codebase? Again, our sense is that it is relatively easy, but we have to look into this.

@danielgoldelman and @Lr-Brown will look into this while @notowen333 is looking into the [training/testing data processing-side of things](https://github.com/privacy-tech-lab/privacy-pioneer/issues/349). The two aspects --- the data processing and the model code --- have to be integrated eventually.

**Comment by notowen333** [comment]
## Discussed today:
- The specific model that we want to integrate is **Multi-label classification**
- We also need to integrate a [tokenizer](https://www.npmjs.com/package/tokenizers) into PP which will be used by the model during run-time inference.

**Comment by danielgoldelman** [comment]
Commit not tracked in the above: save and load via indexeddb
