### ISSUE TITLE
Place Annotation Tool in Shared Context

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#353]
Assuming that we successfully [gather data to train our model](https://github.com/privacy-tech-lab/privacy-pioneer-data-and-scripts/issues/17), we need to annotate that data. We're hoping to have a couple of thousand examples to annotate, so we will want to collaborate.

Before, I explored Docano in #349. If we want to stick to Docano, the task will be to host it using a cloud provider (AWS, Azure, GC, Heroku) or a shared Wesleyan computing resource. Alternatively, if there is an annotating tool that is packaged as a web-app, we could do that too.

**Comment by Lr-Brown** [comment]
Looked into alternatives for doccano and it seemed to be the simplest and enough for our use case. 

> It is less adaptable than tools like brat and WebAnno. It also does not allow for more complex annotation tasks. Duccano does not support relationships between words and nested classifications. However, most production models cannot use this sort of data anyways. What Docanno lacks in customization, it makes up for in simplicity. A simple display allows annotators to select text and choose from a list of keyboard shortcuts to apply an annotation

Therefore, I created an app through Heroku using their single-click deployment button. It clones the entire doccano repo and deploys it to our own heroku project.

The site can be found here: https://privay-pioneer-ta.herokuapp.com/projects

**Comment by SebastianZimmeck** [comment]
Cc'ing @harkous.

**Comment by Lr-Brown** [comment]
Can we add styling to the text that we did not replace with the placeholders?

**Comment by Lr-Brown** [comment]
This issue is completed and a readme is in the works and will be placed in the [privacy-pioneer-annotation](https://github.com/privacy-tech-lab/privacy-pioneer-annotation) repo.
