### ISSUE TITLE
Take other data from ip-api automatically?

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#355]
When a user adds their IP through the affirmative consent button and we query `ip-api`, we actually get a number of data fields. Do we want to also take some of this data as an automation? 

**Neat into our existing taxonomy would be:**

- `regionName`
- `city`
- `zip`

**Maybe interesting**

- `isp`
- `org`

<img width="1146" alt="Screen Shot 2022-03-22 at 3 34 36 PM" src="https://user-images.githubusercontent.com/51685858/159561556-00356d52-e68e-4bb4-ac59-9588f09ef6f1.png">

**Comment by danielgoldelman** [comment]
Justin and I will look into this and come up with a suggestion for next meeting.

**Comment by JustinCasler** [comment]
We already have a similar thing in the crawl, so as a result, many of the necessary steps for regionName, city, zip, etc., are built out. In my opinion, after the user adds their IP using the affirmative consent button, it would be useful to them if we also added some of these other data fields too. Assuming that the crawl's code is somewhat transferable, I think the time spent making this change would be worth it.

As far as isp and org, I don't think isp would be too insightful, and the org field is very infrequently populated with data. I wouldn't pursue either of these much further.

**Comment by SebastianZimmeck** [comment]
For the current state of this issue, see [my comment in the related issue](https://github.com/privacy-tech-lab/privacy-pioneer/issues/362#issuecomment-1141348985).

**Comment by SebastianZimmeck** [comment]
As we discussed today, as we will keep using apistack/iplayer, we might as well use the full data we receive from them. 

Based on our discussion, @danielgoldelman will look into the advantages and disadvantages of supplementing  apistack/iplayer (or whatever IP geolocation service we decided to use) with our own data and how that could play out in the logic of our code and usability.

**Comment by SebastianZimmeck** [comment]
We decided today today to take all data useful to us from ipinfo.io. I believe this question is resolved and remaining points can be discussed in #370.
