### ISSUE TITLE
Location Tooltip Which Suggests VPN Use/Additional Suggestions?

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#356]
## VPN Suggestion
There is an opportunity to suggest to users that the location data that we find is likely related to servers mapping IP to location data. I'm not sure where in the UI it would fit, but maybe we want to suggest that a VPN would reduce the prevalence of the data collection we are showing them.

## Additional Suggestions?
More generally, the same could be brought up about suggesting an Ad Blocker to reduce Monetization labels or other privacy-preserving tools to reduce Tracking labels. It is a little less clear about what to suggest to users for these.

**Comment by SebastianZimmeck** [comment]
These are good points, @notowen333. For me they are long-term. In particular, I was thinking that we could actually advertise privacy-preserving products.
