### ISSUE TITLE
Expand List of Known Pixels

### ISSUE THREAD

**Issue by notowen333** [privacy-tech-lab/privacy-pioneer#359]
For the list-based approach to tracking pixels, there is no reason to not expand the list. Right now, the list comes entirely from this [blog](https://jvns.ca/blog/how-tracking-pixels-work/) plus the Facebook pixel. This is a research-based issue that can be approached at any time.

**Comment by danielgoldelman** [comment]
I have expanded the list of known pixels to include package managers for pixels. See [here](https://docs.google.com/spreadsheets/d/1nrg-8OLwhO_oQ0J-4JyE_oFEegDJmrBhRgBrl8py2ns/edit#gid=0) for the sources of these additions.

**Comment by SebastianZimmeck** [comment]
@JustinCasler will check if it is useful to expand the pixel list based on [builtwith](https://builtwith.com/?tracking+pixel).

**Comment by SebastianZimmeck** [comment]
As discussed, if @danielgoldelman also thinks it is good, we are going to add the pixels from builwith.
