### ISSUE TITLE
Experiment use of an API to extract IP address and region

### ISSUE THREAD

**Issue by danielgoldelman** [privacy-tech-lab/privacy-pioneer#364]
This issue is for the exploration of utilizing some API to extract IP address and region data for a user.

**Comment by SebastianZimmeck** [comment]
I opened an issue, #370, on switching to IPinfo. So, we can experiment with that.

**Comment by SebastianZimmeck** [comment]
We decided today today to take all data useful to us from ipinfo.io. I believe this question is resolved and remaining points can be discussed in #370.
