### ISSUE TITLE
Implement data collection mechanism for usability study

### ISSUE THREAD

**Issue by jjeancharles** [privacy-tech-lab/privacy-pioneer#386]
Exploring how we'll approach the Usability Study

**Things we may need to look at**

- Whether the data will be stored locally or online through backend
- Questions to consider looking at when conducting the usability study
- What is essential to look at in order to improve the Usability Study and the usability of the extension

**Comment by SebastianZimmeck** [comment]
Three more points:

- As we would like to see how the study participants interact with PP, e.g., which features they use and how frequently, *how do we collect the data*? There are essentially two options: (1) locally on the participants' computers or (2) using a backend server. 
   - The first option is quicker to do, does not involve setting up backend, but may be a bit inconvenient to use. For example, data could be stored in the IndexedDB and then have a button for exporting the data into JSON format or something similar. [OptMeowt](https://github.com/privacy-tech-lab/gpc-optmeowt) has such functionality implemented for exporting the list of websites from which a users opts out. We ask the participants to drop that file into a Google Drive. 
   -   The second option could be done via Firebase, for example.
- Another point we need to scope out is whether *we build our own data logging and/or we use Google Analytics* or some other existing technology? If the latter, how can we integrate it? Under which licensing terms is it available? Potential  costs?
- Do we build this *data collection functionality permanently into PP or just for the study*? Maybe, we just include as a feature that needs to be enabled by pushing a button, and for the normal version of PP we just hide that button. That way we could bring on the functionality if we need (e.g., for later studies) it but it would not confuse the normal users.

**Comment by SebastianZimmeck** [comment]
@jjeancharles will explore this issue a bit further and report on findings. Especially, look into:

1. Use of Google analytics 
2. Implementing locally storing user interactions (e.g., when a user clicks on some button in the popup to explore some results). Can we locally create a local history (say in an IndexedDB) of a user's interaction with PP?

**Comment by lr-brown** [comment]
After speaking with Judeley, the changes are in a branch however we have to work on a way to programmatically switch data collection on and off within the extension.
