### ISSUE TITLE
Implement unit testing and continuous integration

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#389]
Once we have finalized PP we should do a comprehensive acceptance test to make sure that all functionality is working, there are no bugs, the UI is understandable, etc. I can imagine that we find a bunch of issues along the lines of #388 that @JustinCasler just opened. The first step is to create a list of what to test for. 

@jjeancharles, please start compiling this list. That is a good way of getting to know PP. Also, if anything is unclear from a usability perspective, e.g., what a certain functionality does, please included it in the list as well. So, this is not limited to bugs but really about everything. @JustinCasler and @danielgoldelman can supplement the list as necessary.

**Comment by jjeancharles** [comment]
- [ ] History (Do filters work, does it show all of the history, search through history, etc)



- Watchlist 

     - [ ] Add Keyword
     - [ ] Phone Number (If user doesn't input the exact format of how the phone number should look like, will this          functionality still work, etc)
     - [ ] Street Address (Whether user puts a valid input [region, zip code, etc], etc)
     - [ ] Alerts

**Comment by lr-brown** [comment]
In a meeting with Justin and Daniel we discussed the possibility of automated QA testing with jest or a similar framework. We can discuss it on Friday.

**Comment by SebastianZimmeck** [comment]
As @lr-brown and @jjeancharles reported, the unit test framework (Jest) and continuous integration (GitHub Actions) is implemented.

Now, @lr-brown and @jjeancharles will write the tests per [above](https://github.com/privacy-tech-lab/privacy-pioneer/issues/389#issuecomment-1219486342). 

Also, @lr-brown will add a section to the readme describing the whole test setup, e.g., 
- Jest
- GitHub Actions
- When tests are run automatically
- How to run tests manually
- How to add, remove, modify tests
- Where are the tests?
...

This description does not need to be long. But someone looking at the repo should be able to understand it.

**Comment by SebastianZimmeck** [comment]
@lr-brown and @jjeancharles, let's finish this within the next days.

**Comment by SebastianZimmeck** [comment]
Let's finish this by next week's meeting. @lr-brown will add documentation, especially, in the readme on how to run the tests and add test cases.

**Comment by lr-brown** [comment]
Added more tests and updated the readMe
