### ISSUE TITLE
Run automated tests whenever a new pull request is created

### ISSUE THREAD

**Issue by lr-brown** [privacy-tech-lab/privacy-pioneer#405]
We want to use git actions to run our testing suite whenever anyone opens a pull request.

**Comment by lr-brown** [comment]
We could also have the option of blocking merges to main if tests fail.

**Comment by SebastianZimmeck** [comment]
Also, it would be nice to have a label in the readme, like the ones from [shields.io](https://shields.io/), saying that all tests have passed. I checked, but so far I could only find labels for test coverage and built success but not test success. Not a must, but nice to have. 

(cc'ing @sophieeng as she is working on testing for OptMeowt)

**Comment by lr-brown** [comment]
implemented with PR-411
