### ISSUE TITLE
Implement pre-usability study usability improvements

### ISSUE THREAD

**Issue by JustinCasler** [privacy-tech-lab/privacy-pioneer#416]
With Privacy Pioneer being finalized shortly, I will take an adversarial approach to our extension and create a document that highlights possible confusing aspects and possible changes that can be made.

**Comment by SebastianZimmeck** [comment]
Here is a [Google Doc](https://docs.google.com/document/d/1vZB5T9ABVu6yij52bGYvyBEaryyuS2ujLCCQskdXgAc/edit?usp=sharing) to collect the findings.

**Comment by SebastianZimmeck** [comment]
As discussed yesterday, @JustinCasler will go ahead with the initial usability fixes.

**Comment by SebastianZimmeck** [comment]
Closing this issue as @JustinCasler has opened individual issues for each of the discussed items.
