### ISSUE TITLE
Fix extension freezing bug that occurs when trying to put in a keyword

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#419]
I went down a rabbit hole of updating various dependencies due to the Dependabot alerts. Most noteworthy, there were breaking changes from `webpack-dev-server` v3 to v4. I got it to work. There are no more errors. But the performance seems to have decreased. My fan turns on quite a bit. When I open the settings page, the extension freezes.

@lr-brown, can you look into this? 

A few points (maybe relevant; maybe not):

- I had a bit difficulty updating brew but then it worked using [this](https://stackoverflow.com/a/40558662).
- I am running node v18.10.0. I used [this](https://stackoverflow.com/a/50621840) to update.
- Important: [Here](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md) is the webpack migration guide. The webpack.config.babel.js is the file to change. That is were all the breaking changes occured.
- I needed to locally add [Bootstrap 5 Popper.js Core](https://stackoverflow.com/a/57460355). Not sure, do we need to add it as a dependency somewhere in the code?

For the future, please let's keep all our dependencies up-to-date. Otherwise, we are ending up with breaking changes and large amounts of Dependabot alerts that make it hard to deal with.

**Comment by SebastianZimmeck** [comment]
The issue-419 branch should work. Though, PP freezes for me when I try to enter a keyword.

**Comment by lr-brown** [comment]
The issue with freezing seems to be a backend issue. I will work with @danielgoldelman and @JustinCasler to figure out how to resolve it. There does't seem to be any issues with the updates you made @SebastianZimmeck.

**Comment by SebastianZimmeck** [comment]
OK, thanks @lr-brown! I will open a PR  for merging the issue-419 branch and add you and @danielgoldelman as reviewers. If the branch does not conflict with anything you are doing, please approve the merge as soon as possible.

**Comment by danielgoldelman** [comment]
Problem is occurring in the backend. I will take lead.

**Comment by SebastianZimmeck** [comment]
I accidentally closed this issue. So, reopened ...

**Comment by SebastianZimmeck** [comment]
Seems this is resolved. Close?
