### ISSUE TITLE
Pre usability study improvements 

### ISSUE THREAD

**Issue by JustinCasler** [privacy-tech-lab/privacy-pioneer#423]
- [x] Add unique pop-up message on home page
<img width="160" alt="Screen Shot 2022-10-16 at 1 07 59 PM" src="https://user-images.githubusercontent.com/97986810/196048607-5f5c5cd5-5d70-45a2-8300-5ae5c2b0ba0b.png">

- [x] Add watchlist hover label for automatically generated keywords
<img width="400" alt="Screen Shot 2022-10-11 at 11 54 22 PM" src="https://user-images.githubusercontent.com/97986810/196048633-69b64a21-1930-41a7-8861-9dff829de97a.png">

- [x] Clarify the purpose or remove the "system default" mode in the viewing options on the settings page 
<img width="250" alt="Screen Shot 2022-10-13 at 11 24 10 PM" src="https://user-images.githubusercontent.com/97986810/196048702-aece760a-5efb-43ef-80cf-4bb37c215cff.png">

**Comment by SebastianZimmeck** [comment]
@JustinCasler, is there anything remaining to do here?

**Comment by SebastianZimmeck** [comment]
> Add watchlist hover label for automatically generated keywords

@JustinCasler, will spend a few more days, and if it cannot be resolved by next week's meeting, we are going to drop it.
