### ISSUE TITLE
Check and fix ML performance after finishing the implementation

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#427]
As we are currently finalizing the implementation, we should check the ML performance again on the test set. In particular, @danielgoldelman fixed the freezing issue and [opened a PR](  https://github.com/privacy-tech-lab/privacy-pioneer/pull/426). As far as I can tell, most of the changes are a refactoring. However, still we should make sure that there is no impact on the ML. This should be done after we finalized the implementation.

**Comment by SebastianZimmeck** [comment]
Is the ML really working? It looks to me I am getting a number of wrong results that I would not have expected.

<img width="477" alt="Screenshot 2022-12-23 at 7 30 46 PM" src="https://user-images.githubusercontent.com/11034003/209408419-68d27bb3-9859-4a56-95d2-dc3a237e1352.png">

<img width="491" alt="Screenshot 2022-12-23 at 8 56 46 PM" src="https://user-images.githubusercontent.com/11034003/209408430-501cbbec-ce34-434b-80e5-8d9314ffcf2d.png">

**Comment by danielgoldelman** [comment]
Ok, so after review it is clear that the ML is working as intended on my end, a fresh pull of Privacy-Pioneer. However, what is being *sent* to the model is not correct. Location data like the evidence above is slipping passed the code that feeds to the model, and data about a user's auto-generated location is not correctly being distributed to the evidence keyval. So the TLDR is simply that the model is working, but the processes before and after are not.

**Comment by SebastianZimmeck** [comment]
> So the TLDR is simply that the model is working, but the processes before and after are not.

Good to hear on the model. If you could fix the issue, @danielgoldelman, that would be great. We can use this issue (or feel free to organize as you see fit).

**Comment by danielgoldelman** [comment]
Yes, I will work within this issue. I will update in Teams.

**Comment by SebastianZimmeck** [comment]
Can this be merged as quickly as possible? I would like to create screenshots (with correct results) for the study.
