### ISSUE TITLE
Fix incorrect IP info

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#439]
<img width="382" alt="Screenshot 2022-12-23 at 10 21 33 PM" src="https://user-images.githubusercontent.com/11034003/209406656-a3d4cfe8-1040-4cd2-abcd-47957185ead9.png">

**Comment by danielgoldelman** [comment]
Note: Check the readme as well to reflect this change

**Comment by danielgoldelman** [comment]
Taken care of in a pr to #427
