### ISSUE TITLE
When does the tour prompt appear?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#445]
It seems the prompt for taking the tour appears upon navigation to the settings? If so, likely some usability study participants will see the prompt and others do not. This should be uniform.

**Comment by jjeancharles** [comment]
The prompt for taking the tour appears every time you go to the home page of Privacy Pioneer when first starting the extension, it should happen for each user.

**Comment by SebastianZimmeck** [comment]
Thanks, @jjeancharles!
