### ISSUE TITLE
Add unit tests for backend functionality 

### ISSUE THREAD

**Issue by JustinCasler** [privacy-tech-lab/privacy-pioneer#470]
- [x] search functions for encoded emails, phone numbers, home addresses 
- [x] ML
- [x] request analysis

**Comment by SebastianZimmeck** [comment]
@JustinCasler will first finish the ML unit test and then take a comprehensive look at the coverage. Once that is all good, we can prepare the new release (#436).

**Comment by JustinCasler** [comment]
The last things that need tests are:

- [ ] ImportSearchData
- [ ] SVG checking
- [ ] tagParent function
