### ISSUE TITLE
Check dependencies and removed unused/barely used ones

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#474]
@wesley-tan, can you check the [dependencies](https://github.com/privacy-tech-lab/privacy-pioneer#9-third-party-libraries-and-resources) and remove the unused ones? Also, if they are just used in minor cases, we should remove them and think if we can do without this functionality or accomplish it without the dependency. We have too many dependencies and the upkeep is too much. @danielgoldelman can help with this issue.

**Comment by SebastianZimmeck** [comment]
If everyone could put into this issue the dependencies they know we use for sure, that would be a good start.

**Comment by wesley-tan** [comment]
[dependency_check.md](https://github.com/privacy-tech-lab/privacy-pioneer/files/10750962/dependency_check.md)

**Comment by wesley-tan** [comment]
Hi! This is the file I've been using as a casual notepad, deleting some dependencies and running the program again, etc.

**Comment by wesley-tan** [comment]
Unused devDependencies
* @babel/register // don't remove
* @babel/runtime // don't remove
* @emotion/babel-plugin // removed
* css-loader // don't remove
* file-loader // don't remove
* jsdoc // removed
* style-loader // don't remove
* web-ext // don't remove
* webpack-cli // don't remove
* webpack-dev-server // don't remove

Do tell me if anyone has used any of the ones that I've said as "removed"!

**Comment by wesley-tan** [comment]
**Unused dependencies**
Caveat: When I say that it's unused, it means that the program seems to work fine without it. 
I did/will be searching into what each dependency does exactly and I've demarcated when something seems unessential to the program running itself but may be a dev tool, etc. Please tell me if you knoow any to be used.

- @jspopper/core
- ansi-regex
- async
- glob-parent
- got
- json-schema
- jsonwebtoken
- loader-utils
- markdown-i
- marked
- node-forge
- react-hint // this seems like a helpful dev tool
- shell-quote 

**Used dependencies** (program does not work if uninstall), I've also noted when an update is available. As updates may disrupt the program (given that some are major updates), I will try to test updating some of them.

- "@tensorflow/tfjs": "^3.20.0" // update available (4.2.0)
- "bootstrap": "^5.2.3", // update available (5.2.3)
- "framer-motion": "^4.0.3", // update available (9.0.1)
- "google-libphonenumber": "^3.2.32", 
- "idb": "^6.0.0", // update available (7.1.1)
- "queue": "^6.0.2", 
- "react": "^17.0.1", // update avalilable (18.2.0)
- "react-dom": "^17.0.1",// update available (18.2.0)
- "react-joyride": "^2.3.1", 
- "react-loading-skeleton": "^2.2.0", // update available (3.1.0)
- "react-router-dom": "^5.2.0", // update available (6.8.0)
- "react-spinners": "^0.11.0", // update available (5.7.4)
- "react-tooltip": "^4.2.21", // update available (5.7.4)
- "styled-components": "^5.2.1"

**Comment by SebastianZimmeck** [comment]
As discussed, if everyone can take a look at the [unused ones](https://github.com/privacy-tech-lab/privacy-pioneer/issues/474#issuecomment-1462390789) and confirm one way or the other.

**Comment by SebastianZimmeck** [comment]
What's up here? @danielgoldelman, @lr-brown, @JustinCasler, and @jjeancharles, please make an explicit statement in the comments here.

**Comment by lr-brown** [comment]
After some research here is what I found: 

- @jspopper/core, react-hint - is not needed as it was most likely an added package as I was experimenting with tooltips
- got - npm uses it
- loader-utils- babel uses it
- ansi-regex - used with jest
- json-schema - used for styled-components, webpack, and eslint 
- glob-parent - webpack
- jsonwebtoken, node-forge, shell-quote & async  - required for web-ext (used for compiling)
- markdown-it & marked- used with jsdoc

Many of these have to do with compiling, development, and non-frontend tasks which would not show up / affect the extension's functionality but are necessary nonetheless (with the exception of the first few packages).

**Comment by SebastianZimmeck** [comment]
Great! Thanks, @lr-brown!

Can you remove @jspopper/core and react-hint? Then, we call it day ...

**Comment by lr-brown** [comment]
committed directly to main
