### ISSUE TITLE
Prepare and test Firefox Add-on store release

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#481]
We want to manually check that the current release is working well, especially, that session storage persists across sessions. @jjeancharles already identified that there is one issue with the notifications that a link to a piece of evidence presumably is not working. The goal is to have everything working by the time of the usability study.

**Comment by jjeancharles** [comment]
The sessions storage appears to be operating as expected when Firefox and the extension are shut down and restarted. The most recent watchlist data from the most recent session as well as the analytics data are all up to date and nothing seems to be going wrong. I had mentioned the notifications last week, and they appear to be functioning, aside from the fact that some Watchlist items are in various categories, which I recalled someone would be working on. Additionally, an issue I came across, is that when viewing previously browsed websites, the information that was previously obtained during a different session is still there, confusing the user as to whether the information is being received during the current session or a previous one.

**Comment by SebastianZimmeck** [comment]
> the information that was previously obtained during a different session is still there, confusing the user as to whether the information is being received during the current session or a previous one.

Let's discuss this point today.

**Comment by SebastianZimmeck** [comment]
Once the remaining small issues are taken care of, @lr-brown will notify @jjeancharles for a final test run. If everything goes well, @lr-brown will do the release v1.1.0 here and on the Firefox Add-on Store (do not forget to change the version number in the manifest). Also, one new screenshot with the categories in the Add-on Store is needed.

**Comment by SebastianZimmeck** [comment]
@lr-brown, from your perspective, is the release ready at this point? Just your testing, @jjeancharles, remains?

**Comment by SebastianZimmeck** [comment]
@lr-brown already did a release, but we need a new minor one because of #500. So, the testing here refers to that newer release. 

@jjeancharles will take the lead on the release (here on GitHub as well as on the Firefox Add-on Store) with possibly the help of @lr-brown.

**Comment by SebastianZimmeck** [comment]
For our usability study, let's not surface the privacy policy analysis functionality to the users to keep the focus on the core functionality and avoid confusion. This can be done, for example, by just hiding all privacy policy analysis buttons and UI elements in the UI. The  privacy policy analysis functionality can still stay in there. Just we do not show it.

**Comment by SebastianZimmeck** [comment]
@jjeancharles will finalize this issue by Sunday night, July  9.

**Comment by SebastianZimmeck** [comment]
@jjeancharles can you also create a v.1.2.1 release here on GitHub?
