### ISSUE TITLE
Change UI and possible code to only have "first party collection" and "first party sharing with third party"

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#500]
When I visit `wendys.com`, I see the below:

<img width="363" alt="Screenshot 2023-05-03 at 2 20 54 PM" src="https://user-images.githubusercontent.com/11034003/236008984-c8b45abc-61dd-4d01-b87b-aad88feb0d8f.png">

I am not quite sure what that means.
- Is sharing location data with a third party different from a third party collection location data?
- Or do we not count region as location (which would be not consistent with what we explain in the readme)? 

This issue was brought up by Debbie, one of the students in my COMP 360 - Information and Security class.

**Comment by SebastianZimmeck** [comment]
@jjeancharles will take the lead on this issue with possibly the help of @lr-brown and @danielgoldelman. 

In instances [like above](https://github.com/privacy-tech-lab/privacy-pioneer/issues/500#issue-1694586873) the text should say "Did not collect location data" instead of "Did not collect or share location data." This should be the case for all data types (location, IP address, ...). 

Any documentation, code comments, etc. should also be changed accordingly.

Finally, the UI should be in alignment with the code logic. So, for example, if the code makes a distinction between "first party sharing data with third parties" and "third parties collecting data" we would need to adjust the logic accordingly. So, this may not purely be a UI issue but involve the analysis as well. If so, it probably makes the most sense to treat the aforementioned cases  the same (i.e., remove any logic distinguishing these two). We could not quite understand the difference. So, others would even have a harder time. If no change in the logic is required, even better. But @jjeancharles, please confirm one way or the other.

**Comment by SebastianZimmeck** [comment]
Another instances to illustrate the point. For [In-N-Out](https://www.in-n-out.com/), the description in the popup (and anywhere else where it occurs) should be "Did not collect tracking data." 

<img width="356" alt="Screenshot 2023-05-06 at 2 40 35 PM" src="https://user-images.githubusercontent.com/11034003/236641372-93ef702f-3c9b-4423-8412-1a5079bd5746.png">

As I discussed with @jjeancharles, in reality this is probably more In-N-Out acting as a controller of the data and the IP address service more as just a processor under the control of In-N-Out. So, from an overall perspective this is actually In-N-Out collecting the IP address and not sharing with a third party. However, I think we should just stick to collection by the first party in cases like these for two reasons: First, it is difficult to distinguish for us when there is a processor-controller situation vs real sharing; they look the same from the outside. Second, from a technical perspective this is sharing to third party and not collecting by a first party because the data goes to servers of the IP service and not In-N-Out.

**Comment by jjeancharles** [comment]
<img width="1277" alt="Screen Shot 2023-05-22 at 3 34 03 PM" src="https://github.com/privacy-tech-lab/privacy-pioneer/assets/93958692/21af2a4f-14a1-4ceb-a659-c8e41e23a06f">
<img width="1279" alt="Screen Shot 2023-05-22 at 3 36 00 PM" src="https://github.com/privacy-tech-lab/privacy-pioneer/assets/93958692/b73fc8c2-6902-4b9d-b47a-2549b71e50ad">

I currently have a branch where I made the changes that were asked for, I just had a question about how do we dictate throughout the extension the circumstances under which First Parties share or collect data and those under which they do not?

**Comment by SebastianZimmeck** [comment]
> I just had a question about how do we dictate throughout the extension the circumstances under which First Parties share or collect data and those under which they do not?

Do you mean how we define first part data (1) collection and (2) sharing? 

Do you have particular scenarios or edge cases in mind?

**Comment by jjeancharles** [comment]
<img width="1280" alt="Screen Shot 2023-05-22 at 4 05 10 PM" src="https://github.com/privacy-tech-lab/privacy-pioneer/assets/93958692/b74523f8-f66c-4dea-8c41-348699cbf6dd">
<img width="1282" alt="Screen Shot 2023-05-22 at 4 05 54 PM" src="https://github.com/privacy-tech-lab/privacy-pioneer/assets/93958692/98228d58-5e80-48d3-8547-d9a41a2776f0">

Looking at these two screenshots, essentially what is the difference between these two? Why doesn't the first screenshot just also say "nytimes shared the following tracking data: "

**Comment by SebastianZimmeck** [comment]
I think the reason is just a formalistic categorization (and that should be changed).

In the first screenshot, we have detected a tracking pixel but no advertising. Detection of tracking pixels depends on a list and heuristics @danielgoldelman created. Advertising, on the other hand, depends on the Disconnect list. Only for the latter we say that it is sharing. In other words, I think we only make the call that data is shared if a site contains an entry from the Disconnect list (I believe, at least, that is how we do it; I am not 100% sure). This is inconsistent, and we should change it. Tracking pixels are also sharing.

More generally, and it would be good if you can look into that as well and correct as necessary, @jjeancharles, for [all our privacy practices](https://github.com/privacy-tech-lab/privacy-pioneer#7-privacy-practice-analysis) (IP address, phone number, ...) the categorization of `sharing` or `not sharing` should not depend on our method of detection.
