### ISSUE TITLE
Add privacy policy analysis feature

### ISSUE THREAD

**Issue by jjeancharles** [privacy-tech-lab/privacy-pioneer#503]
Currently working on a feature that analyzes Privacy Policies, and shows users what information may get collected from the site.

**Comment by SebastianZimmeck** [comment]
We decide over the next few weeks whether we will be moving forward here. If yes, we extend what @jjeancharles' already provided. If not, we should remove the code from the `main` branch, to not get confused later on.

**Comment by jjeancharles** [comment]
We have decided not to move forward with this functionality. I will be closing the issue and the code is under the [policy_analyzer](https://github.com/privacy-tech-lab/privacy-pioneer/tree/policy_analyzer) branch.
