### ISSUE TITLE
Address npm warnings on install, tooltip changes

### ISSUE THREAD

**Issue by danielgoldelman** [privacy-tech-lab/privacy-pioneer#511]
This is a combined issue to address the npm warnings that appear when running ```npm install --production=false``` and address tooltip inconsistencies described in personal communications:

NPM warnings: 
```
npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@3.22.8: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
```

Tooltip discussion:
Some tooltips only describe when keywords are shared with a third party. This should be updated to describe the fact that keywords could be collected by a first party. Other small formatting issues will also be addressed.

**Comment by SebastianZimmeck** [comment]
@danielgoldelman is saying in the Teams chat that the npm warnings relate to deprecated code that will have no affect on our project but will always be downloaded into a project. Even running npm uninstall <dependency> on these warnings has no affect on our code, and they will show up even after running that command.

So, let's make a Known Issues section in the readme and describe the issue there.

Also, the tooltip for the "see all" button speaks of "3rd parties." So, let's make the whole tool-tipery uniform.
