### ISSUE TITLE
Remove unfiltered websites when using companies filter in History View

### ISSUE THREAD

**Issue by jjeancharles** [privacy-tech-lab/privacy-pioneer#518]
When using the companies filter in the History View, it displays every website visited while using PP and does not filter out the sites that does not contain the company that is being filtered.
<img width="1552" alt="Screen Shot 2023-06-27 at 11 36 06 AM" src="https://github.com/privacy-tech-lab/privacy-pioneer/assets/93958692/d581f24e-e2e6-4004-b752-b4df50b05816">

**Comment by jjeancharles** [comment]
Past couple of days I've attempted to solve this issue but having I am having some difficulty. Currently speaking with Logan and @danielgoldelman to help with this issue.

**Comment by SebastianZimmeck** [comment]
@jjeancharles will finalize this issue by Saturday night, July  8.

**Comment by jjeancharles** [comment]
@danielgoldelman helped with fixing this issue, there are still tiny bugs during special cases of using the companies filter and the search filter but overall the extension is functional for now. I will discuss in tomorrow's meeting if we can put the extension on the Mozilla Add-On store.

**Comment by SebastianZimmeck** [comment]
At this point, the remaining edge case fix is low priority.
