### ISSUE TITLE
Address HuggingFace PRs

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#525]
We are getting HuggingFace PRs:
- Adding `safetensors` variant of this model
- https://huggingface.co/privacy-tech-lab/CityDistilledModel/discussions/1#64b5119e0a54158d663d71e4
- https://huggingface.co/privacy-tech-lab/CityModel/discussions/1#64c1d3417e6975b391708580

**Comment by danielgoldelman** [comment]
Addressed.

**Comment by danielgoldelman** [comment]
Addressed.
