### ISSUE TITLE
Fix notifications for phone numbers and IP addresses

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#526]
Per the readme:

> Phone numbers do not currently generate notifications. This will be addressed soon.
> IP addresses sometimes do not generate notifications. This will be addressed soon.

**Comment by jjeancharles** [comment]
I was able to figure out and fix the issue on why phone number labels were not showing. In terms of notifications there is a bug that I am currently dealing with but I'm not too sure if it is just my computer. 

- When creating a new watchlist keyword, the notification alert icon is automatically on and I'm not able to turn it on or off. I also do not receive any notifications from that specific keyword. 

@danielgoldelman @SebastianZimmeck @JoeChampeau are any of you experiencing this issue? If so I will create a new issue and take a look at this.

**Comment by SebastianZimmeck** [comment]
@danielgoldelman, can you check?

**Comment by SebastianZimmeck** [comment]
Or, @JoeChampeau, if you have time and know, please also check.

**Comment by danielgoldelman** [comment]
@jjeancharles I haven't experienced that issue... we will connect separately.
