### ISSUE TITLE
Fix "Save Full HTTP Requests" & "Optimize Performance" buttons

### ISSUE THREAD

**Issue by jjeancharles** [privacy-tech-lab/privacy-pioneer#529]
While looking to verify whether these buttons work as they are supposed to via Overleaf paper draft

> "We only store what we analyze, with one more addition: If the optimize button in the settings page is on, we only store the subsection of the HTTP request string that we show in the frontend. If the button is turned off, we store the full http request string that we analyzed."

1. The optimize performance button does not do what it's claimed to do. When the button is on or off, it only stores the subsection of the HTTP request string that was shown in the front end.

2. When using the "Save Full HTTP Requests" button, the extension seems to not collect any evidence at all.

There are two current solutions, we can either fix the buttons or @SebastianZimmeck suggested we either remove these two buttons from the extension.

**Comment by SebastianZimmeck** [comment]
Here is screenshot of the UI with the buttons @jjeancharles mentions.

<img width="1279" alt="open_issue" src="https://github.com/privacy-tech-lab/privacy-pioneer/assets/11034003/253d68af-55e4-46e9-8181-f6a156815e1e">

> or @SebastianZimmeck suggested we either remove these two buttons from the extension.

If we go that route, we should identify all code related to this functionality --- UI and otherwise --- to remove.

**Comment by JoeChampeau** [comment]
Was a consensus ever reached on this subject? It seems to me like it might make the most sense to remove the buttons - is there any reason a user would ever want anything more than the truncated HTTP request string?

**Comment by jjeancharles** [comment]
@JoeChampeau We have not yet. In my opinion I think we should remove the two buttons but I'm not too sure if there will be any importance depending on what we are aiming for this semester. I never really used the function since I've joined but @danielgoldelman may have a different opinion.

**Comment by SebastianZimmeck** [comment]
Feel free to chime in, @danielgoldelman. As far as I am concerned, yes, let's remove these buttons and any associated code with it. They do not work anyways.

**Comment by danielgoldelman** [comment]
I remember us discussing whether we wanted to allow "power users" or anyone who was inclined to look at the full http requests for research purposes the ability to store the full requests if they desired, but I don't have strong feelings towards this. @JoeChampeau it seems like the consensus is to remove it. Please do.
