### ISSUE TITLE
Implement new icons for X, the artist formerly known as Twitter

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#537]
@jjeancharles, can you look into what we would need here, and go ahead as needed to make the changes anywhere necessary in the codebase?

**Comment by jjeancharles** [comment]
@SebastianZimmeck , I updated the SVG to the current icon and updated the naming of Twitter to X. I will submit a PR that closes this issue.

**Comment by SebastianZimmeck** [comment]
Obliged, @jjeancharles!
