### ISSUE TITLE
Fix notifications for IP and phone numbers (or update readme)

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#547]
The readme currently says:

> Phone numbers do not currently generate notifications. This will be addressed soon.
> IP addresses sometimes do not generate notifications. This will be addressed soon.

**Comment by SebastianZimmeck** [comment]
While a slightly different issue, this issue relates to #549.

**Comment by SebastianZimmeck** [comment]
@JoeChampeau takes a look and determines if this issue can be resolved along the lines of #549. Even if not, @JoeChampeau will explore other solutions. @dadak-dom and @danielgoldelman will review any PR.

**Comment by JoeChampeau** [comment]
PR linked with fix for phone notifications. Once it's approved I'll update the readme. IP notifications, as @jjeancharles noted in #526, are working just fine.

**Comment by SebastianZimmeck** [comment]
Excellent, @JoeChampeau!

**Comment by SebastianZimmeck** [comment]
@JoeChampeau, can you also update the readme as necessary?

For example, it still says "This will be addressed soon."

Also, is there anything else in the readme that needs to be adapated?

**Comment by JoeChampeau** [comment]
Thanks for the reminder @SebastianZimmeck, it should be updated now. I also altered one line in the Notifications section with updated information on some of the changes.

**Comment by SebastianZimmeck** [comment]
Thanks, @JoeChampeau!
