### ISSUE TITLE
Sites with international domains not recognized properly

### ISSUE THREAD

**Issue by dadak-dom** [privacy-tech-lab/privacy-pioneer#552]
I noticed that sites with more than one period in the domain (e.g. https://shopee.com.br) would all get labeled as com.br. Then, these sites all get treated as the same site on the Privacy Pioneer homepage. I'm assuming that the method of parsing the URLs does not account for these kinds of domains.

I would assume this doesn't affect our crawl or its analysis, but it could be a usability problem for international users.

**Comment by SebastianZimmeck** [comment]
Good find, @dadak-dom! This should, indeed, be fixed. If this affects the crawl, we would need to fix it before we start.
