### ISSUE TITLE
Create demo video

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#553]
We should create a one to two-minute demo video on what Privacy Pioneer is and how to use it. We have some [older videos that Logan created](https://drive.google.com/open?id=1i0chXAxBugBiTz38Ql9eOKtAIZc0nxvJ&usp=drive_fs), but those were for the Google talk and are also a bit outdated. I imagine a video like for [Ghostery](https://www.ghostery.com/ghostery-ad-blocker), but with a screen cast and voice over. This may be a good issue for @natelevinson10 to get started next year.

**Comment by natelevinson10** [comment]
I've recorded a demo of the extension using screencasting and a voice over, it can be downloaded by clicking the link below:
https://github.com/privacy-tech-lab/privacy-pioneer/assets/78764811/600a95f4-4d41-4c7e-ba08-eab8e1779ba4

Please do let me know thoughts and if anything should be added/changed in terms of the contents or chronology of the video

**Comment by SebastianZimmeck** [comment]
Nice!

A few minor suggestions:

- You speak of a "crawler," and crawl we will. But the crawler is separate from the extension. What is contained in this repo and what you demonstrated is just the extension. Can you change the narration? Alternatively, maybe while you speak at a text with "The Privacy Pioneer extension is available at https://addons.mozilla.org/en-US/firefox/addon/privacy-pioneer/" or something like that.
- Not a huge issue, but feel free to blur your IP address (partly).
- Also, feel free to include a text (or spoken intro) of you are and who we are "Demoed by Nate Levinson of the privacy-tech-lab" or something like that.

**Comment by natelevinson10** [comment]
Before I re-record, how does this sound for the intro?

"Hello everyone, my name is Nate Levinson of the privacy-tech-lab, and welcome to a brief overview and walkthrough of Privacy Pioneer. Privacy Pioneer is a browser extension that collects and displays evidence of privacy-invasive procedures from companies gathering and sharing personal data. Privacy Pioneer is currently available for download via FireFox Nightly. add-ons"

And there would be text with "The Privacy Pioneer extension is available at https://addons.mozilla.org/en-US/firefox/addon/privacy-pioneer/" as well.

Please let me know how this sounds.

**Comment by SebastianZimmeck** [comment]
Sounds excellent!

**Comment by natelevinson10** [comment]
New recording linked below:

https://github.com/privacy-tech-lab/privacy-pioneer/assets/78764811/9e65311d-a3e3-438a-8390-818c5fbc31a2

Once again please let me know how this looks, thanks

**Comment by SebastianZimmeck** [comment]
Great! I will link it in the readme.
