### ISSUE TITLE
Setting Null Addresses

### ISSUE THREAD

**Issue by JoeChampeau** [privacy-tech-lab/privacy-pioneer#556]
Super minor point revolving around user functionality that I figured I'd raise - currently, the auto-generated IPinfo location data does not include a specific address (it just leaves the field blank), and yet we don't allow users to submit region + city + state/region without also entering an associated address. Some users may not want to do so, or they may want to make alterations to the auto-generated info without having to add in an address. Should we allow this functionality?

**Comment by SebastianZimmeck** [comment]
@JoeChampeau, you mean that IPInfo auto-generated addresses do not include a street?

 >  Should we allow this functionality?

What exact functionality would that be?

**Comment by JoeChampeau** [comment]
@SebastianZimmeck Yes, it does not include a street address. The functionality would be letting users submit Street Address keywords with only City, Region, and ZIP specified
![image](https://github.com/privacy-tech-lab/privacy-pioneer/assets/98630239/6430bf3e-0db5-4cb9-b2b0-439f9bf74920)

**Comment by SebastianZimmeck** [comment]
>  The functionality would be letting users submit Street Address keywords with only City, Region, and ZIP specified

OK, good point, let us do that.
