### ISSUE TITLE
Non-English Characters Handled/Displayed Improperly

### ISSUE THREAD

**Issue by JoeChampeau** [privacy-tech-lab/privacy-pioneer#559]
Just opening an issue for the bug @dadak-dom encountered. It seems to have something to do with characters with diacritics being displayed as their UTF-8 codes. Currently looking into solutions.

**Comment by JoeChampeau** [comment]
Issue seems to be fixed right now - what seems to work is decoding non-ASCII characters in URI-encoded URLs and ensuring general regexes for personal keywords allow for non-English characters. Currently, the URL mutation described above only applies when checking for general keywords (because I want to ensure it doesn't, say, impact the ML model), but after further testing I should be able to determine if this is necessary.

**Comment by JoeChampeau** [comment]
Will re-review, do some extra testing, and produce a revised assessment on the status of this issue and its associated PR before next meeting.

**Comment by SebastianZimmeck** [comment]
@natelevinson10 will work with @JoeChampeau on this issue reviewing the PR (or whatever else you guys determine the appropriate course of action).
