### ISSUE TITLE
Create Citation File

### ISSUE THREAD

**Issue by danielgoldelman** [privacy-tech-lab/privacy-pioneer#573]
Issue to create citation file in Github-supported cff format

**Comment by SebastianZimmeck** [comment]
I realize this is already in there or did you mean something else, @danielgoldelman?

> Sebastian Zimmeck, Daniel Goldelman, Owen Kaplan, Logan Brown, Justin Casler, Judeley Jean-Charles, Joe Champeau and Hamza Harkous, [Website Data Transparency in the Browser](https://sebastianzimmeck.de/zimmeckEtAlPrivacyPioneer2024.pdf), 24th Privacy Enhancing Technologies Symposium (PETS), Bristol, UK and Online Event, July 2024, [BibTeX](https://sebastianzimmeck.de/citations.html#zimmeckEtAlPrivacyPioneer2024Bibtex). If you are using code or interfaces from Privacy Pioneer, please cite this paper. 

Maybe, swap out the title link from my website to the official PETS one:

https://doi.org/10.56553/popets-2024-0048

**Comment by SebastianZimmeck** [comment]
OK, I understand this refers to the cff format per @danielgoldelman's [comment](https://github.com/privacy-tech-lab/privacy-pioneer/pull/574#issuecomment-2052009129).

**Comment by danielgoldelman** [comment]
Yeah, separate formats. I swapped the link titles.
