### ISSUE TITLE
Update package.json to solve Dependabot alert

### ISSUE THREAD

**Issue by atlasharry** [privacy-tech-lab/privacy-pioneer#579]
This issue is for [Dependabot alert 70](https://github.com/privacy-tech-lab/privacy-pioneer/security/dependabot/70).

**Comment by atlasharry** [comment]
I have changed the `ws` and `web-ext` versions in package.lock.json and also package.json. 
However, one thing I noticed is when I build the app according to package.json via `npm install` or `npm install --production=false`, I would ended up creating a totally different package.lock file which has much more than changing only "ws" and "web-ext"  (This may because the current package.lock on our github is outdated?") 

In this branch, I only keep the changes of `ws` and `web-ext` version in the package.lock.json.  Since by updating package.json, the user can build their own app and update the dependencies in package.lock.json accordingly.

I have tested the new dependency versions and the app works perfectly fine on my end.

**Comment by SebastianZimmeck** [comment]
Excellent, @atlasharry!

@atlasharry, can you open a PR and add @dadak-dom as reviewer? 

(cc'ing @Mattm27)

**Comment by SebastianZimmeck** [comment]
[Corresponding OptMeowt issue](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/467) for reference.

**Comment by SebastianZimmeck** [comment]
As discussed, if useful, @atlasharry will also add a comment in the readme for developers on how to fix these type of dependency issues as we will likely continue to see them since we have a good number of dependencies.

**Comment by SebastianZimmeck** [comment]
Thanks, @atlasharry! And once the fix is in, we can close the alert manually.
