### ISSUE TITLE
Fix broken watchlist mute functionality

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/privacy-pioneer#590]
It looks like the watchlist mute functionality is broken. When I mute my email address, as below, I still keep getting alerts. @PattonYin, maybe you can start first checking whether you can replicate that behavior.

<img width="1279" alt="Screenshot 2024-09-02 at 1 23 25 PM" src="https://github.com/user-attachments/assets/ab6cc37e-2167-4c7b-9546-3a97064eda34">

This is a minor issue. I am mostly opening it to not forget it. We have more important issues at the moment.

**Comment by SebastianZimmeck** [comment]
If this proves difficult to pinpoint, just removing the mute functionality completely will work as well. Besides the inconvenience of entering any watchlist keyword again, I do not see a disadvantage (although, we have to make sure; maybe, I am overlooking something).

**Comment by SebastianZimmeck** [comment]
<img width="399" alt="Screenshot 2024-09-25 at 4 29 02 PM" src="https://github.com/user-attachments/assets/3908bd34-b8e8-42b5-bc3d-dd78f9cd97a0">

**Comment by SebastianZimmeck** [comment]
<img width="1291" alt="Screenshot 2024-09-26 at 9 22 36 AM" src="https://github.com/user-attachments/assets/258be352-0594-480e-a646-6d07f3635ca1">

<img width="412" alt="Screenshot 2024-09-26 at 9 20 41 AM" src="https://github.com/user-attachments/assets/3620a382-aba2-453d-8a62-c4f2d692d040">

**Comment by SebastianZimmeck** [comment]
> I was able to reproduce the bug.

OK, great! The next steps are then to find out what causes this behavior and how the code can be changed to make it behave correctly.

**Comment by SebastianZimmeck** [comment]
One other point to consider, @ananafrida. As you mentioned, you could not reproduce the behavior when you installed PP from source and used Firefox Nightly. 

What happens if you install PP from source on normal Firefox?

I am asking because maybe someone already fixed this issue and it is just not yet in the version deployed on the Firefox Add-on store.

**Comment by ananafrida** [comment]
The bug doesn't occur when I install PP in Firefox Nightly. It only occurs when I install PP in normal Firefox. Does that get bring us anywhere?

**Comment by SebastianZimmeck** [comment]
> It only occurs when I install PP in normal Firefox. 

Did you install using the current source code or the version from the Add-on store? 

If you have not tested with the current source code version, is the bug there?

**Comment by ananafrida** [comment]
That's a good point. I haven't tested based on the current source code. I will try that and post updates here.

**Comment by ananafrida** [comment]
I ran the extension locally through the current source code, and the issue persists. The mute functionality doesn't work.

**Comment by SebastianZimmeck** [comment]
OK, then, please try to fix it.
